// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StbTask.proto

package com.eb;

public final class StbTaskOuterClass {
  private StbTaskOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StbTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.eb.StbTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional sint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string taskName = 2;</code>
     */
    java.lang.String getTaskName();
    /**
     * <code>optional string taskName = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaskNameBytes();

    /**
     * <code>optional sint64 createUserId = 3;</code>
     */
    long getCreateUserId();

    /**
     * <code>optional string taskCompleteReason = 4;</code>
     */
    java.lang.String getTaskCompleteReason();
    /**
     * <code>optional string taskCompleteReason = 4;</code>
     */
    com.google.protobuf.ByteString
        getTaskCompleteReasonBytes();

    /**
     * <code>optional string firmwareIds = 5;</code>
     */
    java.lang.String getFirmwareIds();
    /**
     * <code>optional string firmwareIds = 5;</code>
     */
    com.google.protobuf.ByteString
        getFirmwareIdsBytes();

    /**
     * <code>optional sint64 batchOperateId = 6;</code>
     */
    long getBatchOperateId();

    /**
     * <code>optional sint32 status = 7;</code>
     */
    int getStatus();

    /**
     * <code>optional sint32 taskOperateType = 8;</code>
     */
    int getTaskOperateType();

    /**
     * <code>optional string minute = 9;</code>
     */
    java.lang.String getMinute();
    /**
     * <code>optional string minute = 9;</code>
     */
    com.google.protobuf.ByteString
        getMinuteBytes();

    /**
     * <code>optional string hour = 10;</code>
     */
    java.lang.String getHour();
    /**
     * <code>optional string hour = 10;</code>
     */
    com.google.protobuf.ByteString
        getHourBytes();

    /**
     * <code>optional string dates = 11;</code>
     */
    java.lang.String getDates();
    /**
     * <code>optional string dates = 11;</code>
     */
    com.google.protobuf.ByteString
        getDatesBytes();

    /**
     * <code>optional string month = 12;</code>
     */
    java.lang.String getMonth();
    /**
     * <code>optional string month = 12;</code>
     */
    com.google.protobuf.ByteString
        getMonthBytes();

    /**
     * <code>optional string week = 13;</code>
     */
    java.lang.String getWeek();
    /**
     * <code>optional string week = 13;</code>
     */
    com.google.protobuf.ByteString
        getWeekBytes();

    /**
     * <code>optional sint32 typetimes = 14;</code>
     */
    int getTypetimes();

    /**
     * <code>optional sint32 tasktype = 15;</code>
     */
    int getTasktype();

    /**
     * <code>optional string taskparameter = 16;</code>
     */
    java.lang.String getTaskparameter();
    /**
     * <code>optional string taskparameter = 16;</code>
     */
    com.google.protobuf.ByteString
        getTaskparameterBytes();

    /**
     * <code>optional sint64 createTime = 17;</code>
     */
    long getCreateTime();

    /**
     * <code>optional string userGroupMsg = 18;</code>
     */
    java.lang.String getUserGroupMsg();
    /**
     * <code>optional string userGroupMsg = 18;</code>
     */
    com.google.protobuf.ByteString
        getUserGroupMsgBytes();

    /**
     * <code>optional sint32 groupId = 19;</code>
     */
    int getGroupId();
  }
  /**
   * Protobuf type {@code com.eb.StbTask}
   */
  public  static final class StbTask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.eb.StbTask)
      StbTaskOrBuilder {
    // Use StbTask.newBuilder() to construct.
    private StbTask(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private StbTask() {
      id_ = 0L;
      taskName_ = "";
      createUserId_ = 0L;
      taskCompleteReason_ = "";
      firmwareIds_ = "";
      batchOperateId_ = 0L;
      status_ = 0;
      taskOperateType_ = 0;
      minute_ = "";
      hour_ = "";
      dates_ = "";
      month_ = "";
      week_ = "";
      typetimes_ = 0;
      tasktype_ = 0;
      taskparameter_ = "";
      createTime_ = 0L;
      userGroupMsg_ = "";
      groupId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StbTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readSInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              taskName_ = bs;
              break;
            }
            case 24: {

              createUserId_ = input.readSInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();

              taskCompleteReason_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();

              firmwareIds_ = bs;
              break;
            }
            case 48: {

              batchOperateId_ = input.readSInt64();
              break;
            }
            case 56: {

              status_ = input.readSInt32();
              break;
            }
            case 64: {

              taskOperateType_ = input.readSInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();

              minute_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();

              hour_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();

              dates_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();

              month_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();

              week_ = bs;
              break;
            }
            case 112: {

              typetimes_ = input.readSInt32();
              break;
            }
            case 120: {

              tasktype_ = input.readSInt32();
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();

              taskparameter_ = bs;
              break;
            }
            case 136: {

              createTime_ = input.readSInt64();
              break;
            }
            case 146: {
              com.google.protobuf.ByteString bs = input.readBytes();

              userGroupMsg_ = bs;
              break;
            }
            case 152: {

              groupId_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eb.StbTaskOuterClass.internal_static_com_eb_StbTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eb.StbTaskOuterClass.internal_static_com_eb_StbTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eb.StbTaskOuterClass.StbTask.class, com.eb.StbTaskOuterClass.StbTask.Builder.class);
    }

    public static final com.google.protobuf.Parser<StbTask> PARSER =
        new com.google.protobuf.AbstractParser<StbTask>() {
      public StbTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StbTask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StbTask> getParserForType() {
      return PARSER;
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional sint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TASKNAME_FIELD_NUMBER = 2;
    private java.lang.Object taskName_;
    /**
     * <code>optional string taskName = 2;</code>
     */
    public java.lang.String getTaskName() {
      java.lang.Object ref = taskName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string taskName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskNameBytes() {
      java.lang.Object ref = taskName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEUSERID_FIELD_NUMBER = 3;
    private long createUserId_;
    /**
     * <code>optional sint64 createUserId = 3;</code>
     */
    public long getCreateUserId() {
      return createUserId_;
    }

    public static final int TASKCOMPLETEREASON_FIELD_NUMBER = 4;
    private java.lang.Object taskCompleteReason_;
    /**
     * <code>optional string taskCompleteReason = 4;</code>
     */
    public java.lang.String getTaskCompleteReason() {
      java.lang.Object ref = taskCompleteReason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskCompleteReason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string taskCompleteReason = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskCompleteReasonBytes() {
      java.lang.Object ref = taskCompleteReason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskCompleteReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRMWAREIDS_FIELD_NUMBER = 5;
    private java.lang.Object firmwareIds_;
    /**
     * <code>optional string firmwareIds = 5;</code>
     */
    public java.lang.String getFirmwareIds() {
      java.lang.Object ref = firmwareIds_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firmwareIds_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string firmwareIds = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFirmwareIdsBytes() {
      java.lang.Object ref = firmwareIds_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firmwareIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATCHOPERATEID_FIELD_NUMBER = 6;
    private long batchOperateId_;
    /**
     * <code>optional sint64 batchOperateId = 6;</code>
     */
    public long getBatchOperateId() {
      return batchOperateId_;
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;
    /**
     * <code>optional sint32 status = 7;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TASKOPERATETYPE_FIELD_NUMBER = 8;
    private int taskOperateType_;
    /**
     * <code>optional sint32 taskOperateType = 8;</code>
     */
    public int getTaskOperateType() {
      return taskOperateType_;
    }

    public static final int MINUTE_FIELD_NUMBER = 9;
    private java.lang.Object minute_;
    /**
     * <code>optional string minute = 9;</code>
     */
    public java.lang.String getMinute() {
      java.lang.Object ref = minute_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          minute_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string minute = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMinuteBytes() {
      java.lang.Object ref = minute_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minute_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOUR_FIELD_NUMBER = 10;
    private java.lang.Object hour_;
    /**
     * <code>optional string hour = 10;</code>
     */
    public java.lang.String getHour() {
      java.lang.Object ref = hour_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hour_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hour = 10;</code>
     */
    public com.google.protobuf.ByteString
        getHourBytes() {
      java.lang.Object ref = hour_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATES_FIELD_NUMBER = 11;
    private java.lang.Object dates_;
    /**
     * <code>optional string dates = 11;</code>
     */
    public java.lang.String getDates() {
      java.lang.Object ref = dates_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dates_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dates = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDatesBytes() {
      java.lang.Object ref = dates_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dates_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTH_FIELD_NUMBER = 12;
    private java.lang.Object month_;
    /**
     * <code>optional string month = 12;</code>
     */
    public java.lang.String getMonth() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          month_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string month = 12;</code>
     */
    public com.google.protobuf.ByteString
        getMonthBytes() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        month_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEEK_FIELD_NUMBER = 13;
    private java.lang.Object week_;
    /**
     * <code>optional string week = 13;</code>
     */
    public java.lang.String getWeek() {
      java.lang.Object ref = week_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          week_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string week = 13;</code>
     */
    public com.google.protobuf.ByteString
        getWeekBytes() {
      java.lang.Object ref = week_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        week_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPETIMES_FIELD_NUMBER = 14;
    private int typetimes_;
    /**
     * <code>optional sint32 typetimes = 14;</code>
     */
    public int getTypetimes() {
      return typetimes_;
    }

    public static final int TASKTYPE_FIELD_NUMBER = 15;
    private int tasktype_;
    /**
     * <code>optional sint32 tasktype = 15;</code>
     */
    public int getTasktype() {
      return tasktype_;
    }

    public static final int TASKPARAMETER_FIELD_NUMBER = 16;
    private java.lang.Object taskparameter_;
    /**
     * <code>optional string taskparameter = 16;</code>
     */
    public java.lang.String getTaskparameter() {
      java.lang.Object ref = taskparameter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskparameter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string taskparameter = 16;</code>
     */
    public com.google.protobuf.ByteString
        getTaskparameterBytes() {
      java.lang.Object ref = taskparameter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskparameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 17;
    private long createTime_;
    /**
     * <code>optional sint64 createTime = 17;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int USERGROUPMSG_FIELD_NUMBER = 18;
    private java.lang.Object userGroupMsg_;
    /**
     * <code>optional string userGroupMsg = 18;</code>
     */
    public java.lang.String getUserGroupMsg() {
      java.lang.Object ref = userGroupMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userGroupMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userGroupMsg = 18;</code>
     */
    public com.google.protobuf.ByteString
        getUserGroupMsgBytes() {
      java.lang.Object ref = userGroupMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userGroupMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 19;
    private int groupId_;
    /**
     * <code>optional sint32 groupId = 19;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeSInt64(1, id_);
      }
      if (!getTaskNameBytes().isEmpty()) {
        output.writeBytes(2, getTaskNameBytes());
      }
      if (createUserId_ != 0L) {
        output.writeSInt64(3, createUserId_);
      }
      if (!getTaskCompleteReasonBytes().isEmpty()) {
        output.writeBytes(4, getTaskCompleteReasonBytes());
      }
      if (!getFirmwareIdsBytes().isEmpty()) {
        output.writeBytes(5, getFirmwareIdsBytes());
      }
      if (batchOperateId_ != 0L) {
        output.writeSInt64(6, batchOperateId_);
      }
      if (status_ != 0) {
        output.writeSInt32(7, status_);
      }
      if (taskOperateType_ != 0) {
        output.writeSInt32(8, taskOperateType_);
      }
      if (!getMinuteBytes().isEmpty()) {
        output.writeBytes(9, getMinuteBytes());
      }
      if (!getHourBytes().isEmpty()) {
        output.writeBytes(10, getHourBytes());
      }
      if (!getDatesBytes().isEmpty()) {
        output.writeBytes(11, getDatesBytes());
      }
      if (!getMonthBytes().isEmpty()) {
        output.writeBytes(12, getMonthBytes());
      }
      if (!getWeekBytes().isEmpty()) {
        output.writeBytes(13, getWeekBytes());
      }
      if (typetimes_ != 0) {
        output.writeSInt32(14, typetimes_);
      }
      if (tasktype_ != 0) {
        output.writeSInt32(15, tasktype_);
      }
      if (!getTaskparameterBytes().isEmpty()) {
        output.writeBytes(16, getTaskparameterBytes());
      }
      if (createTime_ != 0L) {
        output.writeSInt64(17, createTime_);
      }
      if (!getUserGroupMsgBytes().isEmpty()) {
        output.writeBytes(18, getUserGroupMsgBytes());
      }
      if (groupId_ != 0) {
        output.writeSInt32(19, groupId_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, id_);
      }
      if (!getTaskNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTaskNameBytes());
      }
      if (createUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, createUserId_);
      }
      if (!getTaskCompleteReasonBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTaskCompleteReasonBytes());
      }
      if (!getFirmwareIdsBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFirmwareIdsBytes());
      }
      if (batchOperateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, batchOperateId_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, status_);
      }
      if (taskOperateType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(8, taskOperateType_);
      }
      if (!getMinuteBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMinuteBytes());
      }
      if (!getHourBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getHourBytes());
      }
      if (!getDatesBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getDatesBytes());
      }
      if (!getMonthBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getMonthBytes());
      }
      if (!getWeekBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getWeekBytes());
      }
      if (typetimes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(14, typetimes_);
      }
      if (tasktype_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(15, tasktype_);
      }
      if (!getTaskparameterBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getTaskparameterBytes());
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(17, createTime_);
      }
      if (!getUserGroupMsgBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getUserGroupMsgBytes());
      }
      if (groupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(19, groupId_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eb.StbTaskOuterClass.StbTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eb.StbTaskOuterClass.StbTask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.eb.StbTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.eb.StbTask)
        com.eb.StbTaskOuterClass.StbTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eb.StbTaskOuterClass.internal_static_com_eb_StbTask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eb.StbTaskOuterClass.internal_static_com_eb_StbTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eb.StbTaskOuterClass.StbTask.class, com.eb.StbTaskOuterClass.StbTask.Builder.class);
      }

      // Construct using com.eb.StbTaskOuterClass.StbTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        taskName_ = "";

        createUserId_ = 0L;

        taskCompleteReason_ = "";

        firmwareIds_ = "";

        batchOperateId_ = 0L;

        status_ = 0;

        taskOperateType_ = 0;

        minute_ = "";

        hour_ = "";

        dates_ = "";

        month_ = "";

        week_ = "";

        typetimes_ = 0;

        tasktype_ = 0;

        taskparameter_ = "";

        createTime_ = 0L;

        userGroupMsg_ = "";

        groupId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eb.StbTaskOuterClass.internal_static_com_eb_StbTask_descriptor;
      }

      public com.eb.StbTaskOuterClass.StbTask getDefaultInstanceForType() {
        return com.eb.StbTaskOuterClass.StbTask.getDefaultInstance();
      }

      public com.eb.StbTaskOuterClass.StbTask build() {
        com.eb.StbTaskOuterClass.StbTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eb.StbTaskOuterClass.StbTask buildPartial() {
        com.eb.StbTaskOuterClass.StbTask result = new com.eb.StbTaskOuterClass.StbTask(this);
        result.id_ = id_;
        result.taskName_ = taskName_;
        result.createUserId_ = createUserId_;
        result.taskCompleteReason_ = taskCompleteReason_;
        result.firmwareIds_ = firmwareIds_;
        result.batchOperateId_ = batchOperateId_;
        result.status_ = status_;
        result.taskOperateType_ = taskOperateType_;
        result.minute_ = minute_;
        result.hour_ = hour_;
        result.dates_ = dates_;
        result.month_ = month_;
        result.week_ = week_;
        result.typetimes_ = typetimes_;
        result.tasktype_ = tasktype_;
        result.taskparameter_ = taskparameter_;
        result.createTime_ = createTime_;
        result.userGroupMsg_ = userGroupMsg_;
        result.groupId_ = groupId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eb.StbTaskOuterClass.StbTask) {
          return mergeFrom((com.eb.StbTaskOuterClass.StbTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eb.StbTaskOuterClass.StbTask other) {
        if (other == com.eb.StbTaskOuterClass.StbTask.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTaskName().isEmpty()) {
          taskName_ = other.taskName_;
          onChanged();
        }
        if (other.getCreateUserId() != 0L) {
          setCreateUserId(other.getCreateUserId());
        }
        if (!other.getTaskCompleteReason().isEmpty()) {
          taskCompleteReason_ = other.taskCompleteReason_;
          onChanged();
        }
        if (!other.getFirmwareIds().isEmpty()) {
          firmwareIds_ = other.firmwareIds_;
          onChanged();
        }
        if (other.getBatchOperateId() != 0L) {
          setBatchOperateId(other.getBatchOperateId());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getTaskOperateType() != 0) {
          setTaskOperateType(other.getTaskOperateType());
        }
        if (!other.getMinute().isEmpty()) {
          minute_ = other.minute_;
          onChanged();
        }
        if (!other.getHour().isEmpty()) {
          hour_ = other.hour_;
          onChanged();
        }
        if (!other.getDates().isEmpty()) {
          dates_ = other.dates_;
          onChanged();
        }
        if (!other.getMonth().isEmpty()) {
          month_ = other.month_;
          onChanged();
        }
        if (!other.getWeek().isEmpty()) {
          week_ = other.week_;
          onChanged();
        }
        if (other.getTypetimes() != 0) {
          setTypetimes(other.getTypetimes());
        }
        if (other.getTasktype() != 0) {
          setTasktype(other.getTasktype());
        }
        if (!other.getTaskparameter().isEmpty()) {
          taskparameter_ = other.taskparameter_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (!other.getUserGroupMsg().isEmpty()) {
          userGroupMsg_ = other.userGroupMsg_;
          onChanged();
        }
        if (other.getGroupId() != 0) {
          setGroupId(other.getGroupId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eb.StbTaskOuterClass.StbTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eb.StbTaskOuterClass.StbTask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional sint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional sint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object taskName_ = "";
      /**
       * <code>optional string taskName = 2;</code>
       */
      public java.lang.String getTaskName() {
        java.lang.Object ref = taskName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taskName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaskNameBytes() {
        java.lang.Object ref = taskName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taskName = 2;</code>
       */
      public Builder setTaskName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskName = 2;</code>
       */
      public Builder clearTaskName() {
        
        taskName_ = getDefaultInstance().getTaskName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskName = 2;</code>
       */
      public Builder setTaskNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskName_ = value;
        onChanged();
        return this;
      }

      private long createUserId_ ;
      /**
       * <code>optional sint64 createUserId = 3;</code>
       */
      public long getCreateUserId() {
        return createUserId_;
      }
      /**
       * <code>optional sint64 createUserId = 3;</code>
       */
      public Builder setCreateUserId(long value) {
        
        createUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 createUserId = 3;</code>
       */
      public Builder clearCreateUserId() {
        
        createUserId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object taskCompleteReason_ = "";
      /**
       * <code>optional string taskCompleteReason = 4;</code>
       */
      public java.lang.String getTaskCompleteReason() {
        java.lang.Object ref = taskCompleteReason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskCompleteReason_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taskCompleteReason = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTaskCompleteReasonBytes() {
        java.lang.Object ref = taskCompleteReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskCompleteReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taskCompleteReason = 4;</code>
       */
      public Builder setTaskCompleteReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskCompleteReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskCompleteReason = 4;</code>
       */
      public Builder clearTaskCompleteReason() {
        
        taskCompleteReason_ = getDefaultInstance().getTaskCompleteReason();
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskCompleteReason = 4;</code>
       */
      public Builder setTaskCompleteReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskCompleteReason_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firmwareIds_ = "";
      /**
       * <code>optional string firmwareIds = 5;</code>
       */
      public java.lang.String getFirmwareIds() {
        java.lang.Object ref = firmwareIds_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firmwareIds_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string firmwareIds = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFirmwareIdsBytes() {
        java.lang.Object ref = firmwareIds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firmwareIds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string firmwareIds = 5;</code>
       */
      public Builder setFirmwareIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firmwareIds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string firmwareIds = 5;</code>
       */
      public Builder clearFirmwareIds() {
        
        firmwareIds_ = getDefaultInstance().getFirmwareIds();
        onChanged();
        return this;
      }
      /**
       * <code>optional string firmwareIds = 5;</code>
       */
      public Builder setFirmwareIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firmwareIds_ = value;
        onChanged();
        return this;
      }

      private long batchOperateId_ ;
      /**
       * <code>optional sint64 batchOperateId = 6;</code>
       */
      public long getBatchOperateId() {
        return batchOperateId_;
      }
      /**
       * <code>optional sint64 batchOperateId = 6;</code>
       */
      public Builder setBatchOperateId(long value) {
        
        batchOperateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 batchOperateId = 6;</code>
       */
      public Builder clearBatchOperateId() {
        
        batchOperateId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional sint32 status = 7;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional sint32 status = 7;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 status = 7;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int taskOperateType_ ;
      /**
       * <code>optional sint32 taskOperateType = 8;</code>
       */
      public int getTaskOperateType() {
        return taskOperateType_;
      }
      /**
       * <code>optional sint32 taskOperateType = 8;</code>
       */
      public Builder setTaskOperateType(int value) {
        
        taskOperateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 taskOperateType = 8;</code>
       */
      public Builder clearTaskOperateType() {
        
        taskOperateType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object minute_ = "";
      /**
       * <code>optional string minute = 9;</code>
       */
      public java.lang.String getMinute() {
        java.lang.Object ref = minute_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            minute_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string minute = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMinuteBytes() {
        java.lang.Object ref = minute_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          minute_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string minute = 9;</code>
       */
      public Builder setMinute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        minute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string minute = 9;</code>
       */
      public Builder clearMinute() {
        
        minute_ = getDefaultInstance().getMinute();
        onChanged();
        return this;
      }
      /**
       * <code>optional string minute = 9;</code>
       */
      public Builder setMinuteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        minute_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hour_ = "";
      /**
       * <code>optional string hour = 10;</code>
       */
      public java.lang.String getHour() {
        java.lang.Object ref = hour_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hour_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hour = 10;</code>
       */
      public com.google.protobuf.ByteString
          getHourBytes() {
        java.lang.Object ref = hour_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hour_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hour = 10;</code>
       */
      public Builder setHour(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hour = 10;</code>
       */
      public Builder clearHour() {
        
        hour_ = getDefaultInstance().getHour();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hour = 10;</code>
       */
      public Builder setHourBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hour_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dates_ = "";
      /**
       * <code>optional string dates = 11;</code>
       */
      public java.lang.String getDates() {
        java.lang.Object ref = dates_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dates_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dates = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDatesBytes() {
        java.lang.Object ref = dates_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dates_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dates = 11;</code>
       */
      public Builder setDates(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dates_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dates = 11;</code>
       */
      public Builder clearDates() {
        
        dates_ = getDefaultInstance().getDates();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dates = 11;</code>
       */
      public Builder setDatesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dates_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object month_ = "";
      /**
       * <code>optional string month = 12;</code>
       */
      public java.lang.String getMonth() {
        java.lang.Object ref = month_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            month_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string month = 12;</code>
       */
      public com.google.protobuf.ByteString
          getMonthBytes() {
        java.lang.Object ref = month_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          month_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string month = 12;</code>
       */
      public Builder setMonth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string month = 12;</code>
       */
      public Builder clearMonth() {
        
        month_ = getDefaultInstance().getMonth();
        onChanged();
        return this;
      }
      /**
       * <code>optional string month = 12;</code>
       */
      public Builder setMonthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        month_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object week_ = "";
      /**
       * <code>optional string week = 13;</code>
       */
      public java.lang.String getWeek() {
        java.lang.Object ref = week_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            week_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string week = 13;</code>
       */
      public com.google.protobuf.ByteString
          getWeekBytes() {
        java.lang.Object ref = week_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          week_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string week = 13;</code>
       */
      public Builder setWeek(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        week_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string week = 13;</code>
       */
      public Builder clearWeek() {
        
        week_ = getDefaultInstance().getWeek();
        onChanged();
        return this;
      }
      /**
       * <code>optional string week = 13;</code>
       */
      public Builder setWeekBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        week_ = value;
        onChanged();
        return this;
      }

      private int typetimes_ ;
      /**
       * <code>optional sint32 typetimes = 14;</code>
       */
      public int getTypetimes() {
        return typetimes_;
      }
      /**
       * <code>optional sint32 typetimes = 14;</code>
       */
      public Builder setTypetimes(int value) {
        
        typetimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 typetimes = 14;</code>
       */
      public Builder clearTypetimes() {
        
        typetimes_ = 0;
        onChanged();
        return this;
      }

      private int tasktype_ ;
      /**
       * <code>optional sint32 tasktype = 15;</code>
       */
      public int getTasktype() {
        return tasktype_;
      }
      /**
       * <code>optional sint32 tasktype = 15;</code>
       */
      public Builder setTasktype(int value) {
        
        tasktype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 tasktype = 15;</code>
       */
      public Builder clearTasktype() {
        
        tasktype_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object taskparameter_ = "";
      /**
       * <code>optional string taskparameter = 16;</code>
       */
      public java.lang.String getTaskparameter() {
        java.lang.Object ref = taskparameter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskparameter_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taskparameter = 16;</code>
       */
      public com.google.protobuf.ByteString
          getTaskparameterBytes() {
        java.lang.Object ref = taskparameter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskparameter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taskparameter = 16;</code>
       */
      public Builder setTaskparameter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskparameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskparameter = 16;</code>
       */
      public Builder clearTaskparameter() {
        
        taskparameter_ = getDefaultInstance().getTaskparameter();
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskparameter = 16;</code>
       */
      public Builder setTaskparameterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskparameter_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional sint64 createTime = 17;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional sint64 createTime = 17;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 createTime = 17;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userGroupMsg_ = "";
      /**
       * <code>optional string userGroupMsg = 18;</code>
       */
      public java.lang.String getUserGroupMsg() {
        java.lang.Object ref = userGroupMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userGroupMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userGroupMsg = 18;</code>
       */
      public com.google.protobuf.ByteString
          getUserGroupMsgBytes() {
        java.lang.Object ref = userGroupMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userGroupMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userGroupMsg = 18;</code>
       */
      public Builder setUserGroupMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userGroupMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userGroupMsg = 18;</code>
       */
      public Builder clearUserGroupMsg() {
        
        userGroupMsg_ = getDefaultInstance().getUserGroupMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userGroupMsg = 18;</code>
       */
      public Builder setUserGroupMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userGroupMsg_ = value;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>optional sint32 groupId = 19;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional sint32 groupId = 19;</code>
       */
      public Builder setGroupId(int value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 groupId = 19;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.eb.StbTask)
    }

    // @@protoc_insertion_point(class_scope:com.eb.StbTask)
    private static final com.eb.StbTaskOuterClass.StbTask defaultInstance;static {
      defaultInstance = new com.eb.StbTaskOuterClass.StbTask();
    }

    public static com.eb.StbTaskOuterClass.StbTask getDefaultInstance() {
      return defaultInstance;
    }

    public com.eb.StbTaskOuterClass.StbTask getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eb_StbTask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_eb_StbTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStbTask.proto\022\006com.eb\"\360\002\n\007StbTask\022\n\n\002i" +
      "d\030\001 \001(\022\022\020\n\010taskName\030\002 \001(\t\022\024\n\014createUserI" +
      "d\030\003 \001(\022\022\032\n\022taskCompleteReason\030\004 \001(\t\022\023\n\013f" +
      "irmwareIds\030\005 \001(\t\022\026\n\016batchOperateId\030\006 \001(\022" +
      "\022\016\n\006status\030\007 \001(\021\022\027\n\017taskOperateType\030\010 \001(" +
      "\021\022\016\n\006minute\030\t \001(\t\022\014\n\004hour\030\n \001(\t\022\r\n\005dates" +
      "\030\013 \001(\t\022\r\n\005month\030\014 \001(\t\022\014\n\004week\030\r \001(\t\022\021\n\tt" +
      "ypetimes\030\016 \001(\021\022\020\n\010tasktype\030\017 \001(\021\022\025\n\rtask" +
      "parameter\030\020 \001(\t\022\022\n\ncreateTime\030\021 \001(\022\022\024\n\014u" +
      "serGroupMsg\030\022 \001(\t\022\017\n\007groupId\030\023 \001(\021b\006prot",
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_eb_StbTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_eb_StbTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_eb_StbTask_descriptor,
        new java.lang.String[] { "Id", "TaskName", "CreateUserId", "TaskCompleteReason", "FirmwareIds", "BatchOperateId", "Status", "TaskOperateType", "Minute", "Hour", "Dates", "Month", "Week", "Typetimes", "Tasktype", "Taskparameter", "CreateTime", "UserGroupMsg", "GroupId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
